### ISSUE TITLE
Wrong RTC driver in config for ZX3

### ISSUE THREAD

**Issue by tsat-psv** [enclustra-bsp/xilinx-linux#12]
Hi, it seems that you may have the the wrong driver for the onboard RTC on the Zynq ZX3 module.

I have solved it with the following:

```diff
--CONFIG_RTC_DRV_PCF8563=y
++CONFIG_RTC_DRV_ISL12022=y
```

Please let me know if I should provide a PR.

**Comment by tholzsche** [comment]
Thanks for the info, as far as I know the default configurations were used. But since we are working on a major update and will try to take this into account.

**Comment by tsat-psv** [comment]
No problem. We started using the RTC now, and only noticed that the config was wrong and and the RTC didn't work. 

I have also this PR https://github.com/enclustra-bsp/xilinx-linux/pull/7 that your colleague seems to have accepted that you might consider including in the next update.

**Comment by tsat-psv** [comment]
Should I close this @tholzsche ? I recon this should be resolved in your `update` branches.

**Comment by tholzsche** [comment]
It is covered in the i2c appnote (see https://github.com/enclustra/I2CAppNote/blob/master/Chapter-5-Linux.md#52-rtc)

**Comment by tsat-psv** [comment]
Thanks, looking forward to the update release.
