### ISSUE TITLE
 Zynq UltraScale+ MPSoC: Linux Kernel crashes when running PTP and establishing SSH

### ISSUE THREAD

**Issue by j4munoz** [enclustra-bsp/xilinx-linux#3]
Hello, I got a kernel crash (4.14.0, tag v1.8.1) when PTP is running and I try to establish an SSH session. This seems related to https://www.xilinx.com/support/answers/71510.html. Apparently "There is an issue with the PTP mainline implementation, where all TX packets are timestamped once the PTP application is started."
I applied this patch (https://www.xilinx.com/Attachment/0001-net-macb-Process-tx-timestamp-only-on-ptp-packets.patch) to the kernel and now I am able to SSH into the board (PE1+XU1) successfully.

**Comment by j4munoz** [comment]
I think this is related to issue #4. I reverted the aforementioned patch, and updated the phy drivers from the Kernel repository version 4.14.106.

**Comment by tgorochowik** [comment]
Thank you for your report!

Similarly to https://github.com/enclustra-bsp/xilinx-linux/issues/4, after merging the Linux repo to the latest release from Xilinx the patch you mention is now part of our master branch (see: https://github.com/enclustra-bsp/xilinx-linux/commit/835b6170df72dc73d9386b5838e7f16c09953b9a)

Feel free to use the master branch for the latest code!
